FROM node:12-alpine
WORKDIR /tmp
COPY package.json .
RUN npm install
COPY . .
ARG GOOGLE_OAUTH_CLIENT_ID
RUN sed "s+GOOGLE_OAUTH_CLIENT_ID+$GOOGLE_OAUTH_CLIENT_ID+g" src/.index.html > src/index.html
EXPOSE 4200
CMD npm start
