version: '3.1'

services:
  gcp-dac:
    image: gcr.io/tranquility-base-images/tb-gcp-dac:experimental
    environment:
      HOUSTON_SERVICE_URL: 'houston-service:3000'
    ports:
      - 3100:3100

  tb-db:
    image: gcr.io/tranquility-base-images/tb-db:experimental
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: eagle-user
      MYSQL_PASSWORD: eagle-user-secret-pw
      MYSQL_DATABASE: eagle_db
    ports:
      - 3306:3306

  houston-service:
    image: gcr.io/tranquility-base-images/tb-houston-service:experimental
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://eagle-user:eagle-user-secret-pw@tb-db/eagle_db'
      SQLALCHEMY_ECHO: 'False'
      SQLALCHEMY_TRACK_MODIFICATIONS: 'False'
      GCP_DAC_URL: 'gcp-dac:3100'
    depends_on:
      - tb-db
      - gcp-dac
    ports:
      - 3000:3000
