# This workflow will run tests when a PR is performed.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Eagle Console - TEST Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@master
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies and run tests
      run: |
        npm install
        npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
    - name: Validate the build for production
      run: npm run build
